### ISSUE TITLE
Remove snapping restart of autoscroll

### ISSUE THREAD

**Issue by Antricks** [MoFa-Development/plan-b#23]
It would be awesome if the auto-scroll mode wrapped the substitutions back around, so there's no jumping or moving back. Moving back is also an option of course, but it wouldn't be so cool.

**Comment by SpyrexDE** [comment]
Sounds good. Maybe insert a seperation line as soon as the end loop is reached.

**Comment by Antricks** [comment]
All the ways I see for infinite scrolling are some dirty workarounds. No wonder... it's a pretty special thing I want here. I think it's a better idea to smoothly scroll to the top before going down again instead.

**Comment by SpyrexDE** [comment]
Already tried this solution?
https://stackoverflow.com/a/64536089/12315358

**Comment by Antricks** [comment]
Here's an implementation using just the needed amount of clones at the end + jumping back to 0 at the correct spot. Unfortunately, it does not respond to changing window size yet.

**Comment by Antricks** [comment]
That's all I wanted to implement. This feature is stable.

**Comment by Antricks** [comment]
For some reason, it doesn't jump where it belongs to, so there's a snapping restart again...

**Comment by Antricks** [comment]
This issue is no longer existent on Firefox, Chrome(/-ium) and Safari.
