### ISSUE TITLE
Improve white theme

### ISSUE THREAD

**Issue by SpyrexDE** [MoFa-Development/plan-b#26]
Tbh, I hate our current white theme:
<samp>It's looking kinda dirty and dry</samp>
<img width=500 src="https://user-images.githubusercontent.com/57133330/143773103-04e0cbad-d515-4e18-8a4d-7d9456e54540.png"/>

I just created a prototype in the dev tools:
<samp>How I would like it to be</samp>
<img width=500 src="https://user-images.githubusercontent.com/57133330/143773009-9a86cf9c-dd02-4264-9750-f8396ebc00e5.png"/>

**Comment by Antricks** [comment]
I'm not really convinced tbh. I'd prefer the first option still.

**Comment by SpyrexDE** [comment]
Time for a theme system I would say 🤷‍♂️

**Comment by Antricks** [comment]
I think the basic design of the bright mode is okay, it just needs some tweaking imo.
