### ISSUE TITLE
Weird alignment swapping on resize

### ISSUE THREAD

**Issue by SpyrexDE** [MoFa-Development/plan-b#27]
![Animation](https://user-images.githubusercontent.com/57133330/143869155-6752acbe-f9e4-4087-aee1-5185f78920ce.gif)

**Comment by Antricks** [comment]
Strange, can't reproduce that though... I tried Chromium and Firefox.

**Comment by SpyrexDE** [comment]
Seems to only exist when zoomed with ctrl + scroll I guess?
